### ISSUE TITLE
postinstallation (and thus DevTools) broken by Brotli compression of omni.ja contents

### ISSUE THREAD

**Issue by mykmelez** [mozilla/qbrt#132]
https://bugzilla.mozilla.org/show_bug.cgi?id=1352595 broke postinstallation, which expands Firefox's omni.ja file in order to reuse its devtools.

I don't know of an easy fix; presumably we'd need to find (or build) a ZIP archive expander that knows how to decompress files compressed with the Brotli algorithm.

Probably the better solution is to integrate devtools via https://github.com/devtools-html/devtools, once that becomes available.

**Comment by etiennepinchon** [comment]
Still no way around this issue?

**Comment by mykmelez** [comment]
Brotli compression has been backed out of Firefox, so this should now work in theory, but it still doesn't work after I reverted the change that disabled devtools over in https://github.com/mykmelez/qbrt/tree/reenable-devtools.

So I'm unsure what else is broken. Nevertheless, I still think that the better solution is to integrate devtools via https://github.com/devtools-html/devtools, once that becomes available (assuming it does become available), rather than hackily using the devtools instance built into Firefox.

**Comment by benfrancis** [comment]
@mykmelez  A fix for this would be welcome. This limitation (and other regressions) forced me to switch to Electron :(

**Comment by mykmelez** [comment]
I took another look tonight and resolved the regressions, so DevTools will be back once #153 lands.

That being said, the integration remains brittle and prone to bustage. We'll really need something better. Unfortunately, I don't think #101 is going to be that thing, as the DevTools Go Faster project doesn't seem to have happened.

**Comment by benfrancis** [comment]
I can confirm this is working again, thank you! Now I can debug some other problems...
