### ISSUE TITLE
Status (Discontinued?)

### ISSUE THREAD

**Issue by Happy-Ferret** [mozilla/qbrt#140]
From the lack of activity in the past few months, I assume this project has been abandoned now?
@mykmelez ?

**Comment by mykmelez** [comment]
I've now updated dependencies and also re-enabled DevTools. This issue wasn't necessarily tracking that work, but in any case it's done. I'll close this issue and continue to work on #151 so you can ask this question in a chat room the next time you don't see any activity for a while! ;-)

**Comment by Happy-Ferret** [comment]
Alright.

I'll work on my runtime today, too. Hoping to publish it soon. I'm sure there will be some technology sharing we can do.

**Comment by filips123** [comment]
@mykmelez It looks like development is stalled again as the last commit was in April. Can you resume it?

If qbrt would get access to Node.js APIs it could be a very good alternative for Electron and similar projects.
