### ISSUE TITLE
make it optional to have package.json file

### ISSUE THREAD

**Issue by mykmelez** [mozilla/qbrt#50]
#40 makes it optional to specify a main entry script in your package.json file (by defaulting index.js in that case). We could go further and make it optional to provide a package.json file at all, since none of its properties are necessary when you're running an app. (Packaging is somewhat different, since you presumably want your app to have a name, although even there we could fall back to a default name if one isn't provided.)

**Comment by cvan** [comment]
> (Packaging is somewhat different, since you presumably want your app to have a name, although even there we could fall back to a default name if one isn't provided.)

could grab the name of the target directory (or the current working directory `qbrt` is run from) or its parent.

or another approach - admittedly overboard though - could be to generate the App Name (or Product Name) from a handful of `<meta>` (Microdata) tags, falling back to `document.title` ([see this example](https://github.com/cvan/websdk/blob/d1386c7/src/lib/utils.js#L173)).

**Comment by mykmelez** [comment]
> could grab the name of the target directory (or the current working directory qbrt is run from) or its parent.

Good point, that'd be a useful fallback.

> or another approach - admittedly overboard though - could be to generate the App Name (or Product Name) from a handful of <meta> (Microdata) tags, falling back to document.title (see this example).

Hmm, that could make sense as well, although it seems a bit brittle, as those elements are non-standard (except for document.title).

Out of curiosity, what is websdk?

**Comment by cvan** [comment]
> Out of curiosity, what is websdk?

Just a personal project of a bunch of helpers for common tasks (fetching W3C Web-App Manifests, installing desktop apps, sending SMS, etc.).

**Comment by mykmelez** [comment]
@dmarcos you might be interested in this feature request as well.
