### ISSUE TITLE
test `xvfb-maybe` library to possibly address TaskCluster failures

### ISSUE THREAD

**Issue by cvan** [mozilla/qbrt#57]
I found this in a random, unrelated GitHub issue: https://github.com/paulcbetts/xvfb-maybe might help, though I haven't tried yet.

**Comment by mykmelez** [comment]
TaskCluster seems to have stopped failing on Linux, so I re-enabled it there. I'm not sure what the problem was, but I'll close this for now. If the failures reappear, another option would be to try running Firefox in its new headless mode, so we don't need xfvb to run them.
